steps:
  - label: ":package: Restore dependencies"
    command: "dotnet restore"
    key: "deps"

  - label: ":construction_worker: Build"
    command: "dotnet build --configuration Release --no-restore"
    depends_on: "deps"

  - label: ":white_check_mark: Run tests"
    command: "dotnet test --no-restore --verbosity normal"
    depends_on: "deps"
