steps:
  - label: ":golang: Install dependencies"
    key: "deps"
    command: "go mod vendor"
    plugins:
      - artifacts#v1.9.3:
          upload: "vendor"
          compressed: vendor.tgz
      - docker#v5.9.0:
          image: "golang:1.22"

  - label: ":golang: Build"
    command: "go build -mod=vendor main.go"
    depends_on: ["deps"]
    plugins:
      - artifacts#v1.9.3:
          download: "vendor"
          compressed: vendor.tgz
      - docker#v5.9.0:
          image: "golang:1.22"

  - label: ":golang: Test"
    command: "go test -mod=vendor ./..."
    depends_on: ["deps"]
    plugins:
      - artifacts#v1.9.3:
          download: "vendor"
          compressed: vendor.tgz
      - docker#v5.9.0:
          image: "golang:1.22"

  - label: ":golang: Generate"
    depends_on: ["deps"]
    command:
      - "go generate -mod=vendor ./..."
      - "git diff --exit-code || (echo 'Generated code is out of date, please run `go generate` and commit the changes' && exit 1)"
    plugins:
      - artifacts#v1.9.3:
          download: "vendor"
          compressed: vendor.tgz
      - docker#v5.9.0:
          image: "golang:1.22"
