steps:
  - label: ":golang: Install"
    key: "deps"
    command: "go install"
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Build"
    command: "go build main.go"
    depends_on: ["deps"]
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Test"
    command: "go test ."
    depends_on: ["deps"]
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Go generate check"
    commands:
      - go generate ./...
      - git diff --exit-code || (echo 'Generated code is out of date, please run `go generate` and commit the changes' && exit 1)
    depends_on: ["deps"]
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"