steps:
  - label: ":golang: Install"
    key: "deps"
    command: "go install"
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Build"
    command: "go build main.go"
    depends_on: ["deps"]
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Test"
    command: "go test ."
    depends_on: ["deps"]
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"