steps:
  - label: ":golang: Install dependencies"
    key: "deps"
    command: "go mod vendor"
    plugins:
      - cache#v0.6.0:
          manifest: go.sum
          path: vendor
          restore: file
          save: file
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Build"
    command: "go build -mod=vendor main.go"
    depends_on: ["deps"]
    plugins:
      - cache#v0.6.0:
          manifest: go.sum
          path: vendor
          restore: file
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Test"
    command: "go test -mod=vendor ./..."
    depends_on: ["deps"]
    plugins:
      - cache#v0.6.0:
          manifest: go.sum
          path: vendor
          restore: file
      - docker#v5.9.0:
          image: "golang:latest"

  - label: ":golang: Generate"
    depends_on: ["deps"]
    command:
      - "go generate -mod=vendor ./..."
      - "git diff --exit-code || (echo 'Generated code is out of date, please run `go generate` and commit the changes' && exit 1)"
    plugins:
      - docker#v5.9.0:
          image: "golang:latest"
