steps:
  - label: ":npm: Install dependencies"
    command: "npm install"
    plugins:
      - cache#v0.6.0:
          manifest: package-lock.json
          path: node_modules
          restore: file
          save: file
  - wait
  - label: ":jest: Run unit tests"
    command: "npm run test"
    plugins:
      - cache#v0.6.0:
          manifest: package-lock.json
          path: node_modules
          restore: file
      - docker#v5.9.0:
          image: "node:latest"
  - label: ":eslint: Run ESLint"
    command: "eslint ."
    plugins:
      - cache#v0.6.0:
          manifest: package-lock.json
          path: node_modules
          restore: file
