steps:
  - label: ':swift: Lint'
    command: 'swiftlint'
  - label: ':swift: Test'
    command: 'xcodebuild test -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 11''
  - label: ':swift: Build'
    command: 'xcodebuild -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 11''