env:
  VERCEL_ORG_ID: xxx
  VERCEL_PROJECT_ID: xxx

steps:
  - label: ":vercel: Pull Vercel environment information"
    command: npx vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

  - label: ":vercel: Build project artifacts"
    command: npx vercel build --prod --token="$VERCEL_TOKEN"
    artifacts_path: ".vercel/output"

  - label: Deploy project artifacts to Vercel
    if: build.branch == "main"
    command: npx vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
    plugins:
      - artifacts#v1.9.2:
        download: ".vercel/output"
