steps:
  - group: "Validate"
    key: "validate"
    steps:
      - label: ":buildkite: Validate pipelines"
        command: deno run -A --quiet validate-pipeline.ts
        plugins: &deno
          - docker#v5.9.0:
              image: "denoland/deno:1.38.0"

      - label: ":markdown: Validate content"
        command: deno run -A --quiet validate-template.ts
        plugins: *deno

  - label: ":datocms: Publish content"
    depends_on: "validate"
    command: deno run -A --quiet publish.ts
    if: build.branch == "main"
    plugins: *deno
