steps:
  - label: ":buildkite: Validate pipelines"
    key: "validate"
    command: deno run -A --quiet validate.ts
    plugins:
      - docker#v5.9.0:
          image: "denoland/deno:1.38.0"

  - label: ":datocms: Publish content"
    depends_on: "validate"
    command: deno run -A --quiet publish.ts
    if: build.branch == "main"
    plugins:
      - docker#v5.9.0:
          image: "denoland/deno:1.38.0"
          environment:
            - DATO_API_TOKEN
