steps:
  - group: "Validate"
    key: "validate"
    steps:
      - label: ":buildkite: Validate pipelines"
        command: deno run --check -A --quiet .buildkite/validatePipeline.ts
        plugins: &deno
          - docker#v5.9.0:
              image: "denoland/deno:1.38.0"
              environment:
                - DATO_API_TOKEN

      - label: ":markdown: Validate content"
        command: deno run -A --quiet .buildkite/validateContent.ts
        plugins: *deno

  - label: ":puppeteer: Capture screenshots"
    # if: build.branch == "main"
    depends_on: "validate"
    key: "screenshots"
    commands:
      - PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts
      - deno run --check -A --quiet .buildkite/captureScreenshots.ts
    plugins: *deno
    artifact_paths: "screenshots/*.png"

  - group: "Publish"
    key: "publish"
    depends_on: ["validate", "screenshots"]
    if: build.branch == "main"
    steps:
      - label: ":datocms: Publish templates"
        command: deno run --check -A --quiet .buildkite/publishContent.ts
        plugins: *deno

      - label: ":datocms: Publish categories"
        command: deno run --check -A --quiet .buildkite/publishCategories.ts
        plugins: *deno

  - trigger: "site"
    depends_on: "publish"
    if: build.branch == "main"
    label: ":buildkite: Trigger site build"
    build:
      message: "Triggered by buildkite/templates"
