steps:
  - group: "Validate"
    key: "validate"
    steps:
      - label: ":buildkite: Validate pipelines"
        command: npm run validatePipeline
        plugins: &deno
          - docker#v5.9.0:
              image: "denoland/deno:1.38.0"
              environment:
                - DATO_API_TOKEN

      - label: ":markdown: Validate content"
        command: npm run validateContent
        plugins: *deno

  - group: "Publish"
    key: "publish"
    depends_on: "validate"
    steps:
      - label: ":datocms: Publish templates"
        command: npm run publishTemplates
        if: build.branch == "main"
        plugins: *deno

      - label: ":datocms: Publish categories"
        command: npm run publishCategories
        if: build.branch == "main"
        plugins: *deno

  - trigger: "site"
    depends_on: "publish"
    if: build.branch == "main"
    label: ":buildkite: Trigger site build"
    build:
      message: "Triggered by buildkite/templates"
