steps:
  - group: "Validate"
    key: "validate"
    steps:
      - label: ":buildkite: Validate pipelines"
        command: npm run validatePipeline
        plugins: &node
          - docker#v5.9.0:
              image: "node:21-alpine"
              environment:
                - DATO_API_TOKEN

      - label: ":markdown: Validate content"
        command: npm run validateContent
        plugins: *node

  - group: "Publish"
    key: "publish"
    depends_on: "validate"
    steps:
      - label: ":datocms: Publish templates"
        command: npm run publishTemplates
        if: build.branch == "main"
        plugins: *node

      - label: ":datocms: Publish categories"
        command: npm run publishCategories
        if: build.branch == "main"
        plugins: *node

  - trigger: "site"
    depends_on: "publish"
    if: build.branch == "main"
    label: ":buildkite: Trigger site build"
    build:
      message: "Triggered by buildkite/templates"
