steps:
  - label: ":swift: Lint"
    command: "swiftlint"

  - label: ":swift: Test"
    command: "swift test"
    plugins:
      - docker#v5.9.0:
          image: "swift:latest"

  - wait

  - label: ":swift: Build"
    command: "xcodebuild -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 11'"