steps:
  - label: ":swift: Lint"
    command: "swiftlint"

  - label: ":swift: Test"
    command: "swift test"
    plugins:
      - docker#v5.9.0:
          image: "swift:latest"

  - label: ":swift: Build"
    command: "swift build"
    plugins:
      - docker#v5.9.0:
          image: "swift:latest"