env:
  VERCEL_ORG_ID: xxx
  VERCEL_PROJECT_ID: xxx

steps:
  - label: ":vercel: Build preview"
    command:
      - npx vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
      - npx vercel build --token="$VERCEL_TOKEN"
    plugins:
      - artifacts#v1.9.2:
          upload: ".vercel/output"
          compressed: .vercel/output.tgz

  - label: Deploy preview
    depends_on: "build"
    if: build.branch != "main"
    command: npx vercel deploy --prebuilt --token="$VERCEL_TOKEN"
    plugins:
      - artifacts#v1.9.2:
          download: ".vercel/output"
          compressed: .vercel/output.tgz
