env:
  VERCEL_ORG_ID:
  VERCEL_PROJECT_ID:

steps:
  - label: ":vercel: Build preview"
    command:
      - npx vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
      - npx vercel build --prod --token="$VERCEL_TOKEN"
    artifacts_path: ".vercel/output"

  - label: Deploy preview
    if: build.branch != "main"
    command: npx vercel deploy --prebuilt --token="$VERCEL_TOKEN"
    plugins:
      - artifacts#v1.9.2:
        download: ".vercel/output"
