env:
  RUBY_VERSION: latest

steps:
  - label: ":ruby: Install gems"
    command: "bundle install"
    key: "gems"
    plugins:
      - docker#v5.9.0:
          image: "ruby-slim:$RUBY_VERSION"
      - cache#v0.6.0:
          manifest: Gemfile.lock
          path: vendor/bundle
          restore: file
          save: file

  - label: ":rubocop: Run rubocop"
    command: "bundle exec rubocop"
    depends_on: "gems"
    plugins:
      - docker#v5.9.0:
          image: "ruby-slim:$RUBY_VERSION"
      - cache#v0.6.0:
          manifest: Gemfile.lock
          path: vendor/bundle
          restore: file

  - label: ":rspec: Run rspec"
    command: "bundle exec rspec"
    depends_on: "gems"
    plugins:
      - docker#v5.9.0:
          image: "ruby-slim:$RUBY_VERSION"
      - cache#v0.6.0:
          manifest: Gemfile.lock
          path: vendor/bundle
          restore: file
