steps:
  - label: ":vercel: Build"
    key: "build"
    command:
      - npx vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
      - npx vercel build --prod --token="$VERCEL_TOKEN"
    plugins:
      - artifacts#v1.9.2:
          upload: ".vercel/output"
          compressed: .vercel/output.tgz

  - label: ":vercel: Deploy"
    depends_on: "build"
    if: build.branch == "main"
    command: npx vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
    plugins:
      - artifacts#v1.9.2:
          download: ".vercel/output"
          compressed: .vercel/output.tgz
