steps:
  - label: ":composer: Install packages"
    key: "composer"
    command: "composer install"
    plugins:
      - docker#v5.9.0:
          image: "composer:latest"
      - artifacts#v1.9.3:
          upload: "vendor"
          compressed: vendor.tgz

  - label: ":php: Lint"
    depends_on: "composer"
    command: 'find -name "*.php" -not -path "./vendor/*" | xargs php -l'
    plugins:
      - docker#v5.9.0:
          image: "php:latest"
      - artifacts#v1.9.3:
          download: "vendor"
          compressed: vendor.tgz

  - label: ":phpunit: Run phpunit"
    depends_on: "composer"
    command: "vendor/bin/phpunit --configuration phpunit.xml"
    plugins:
      - docker#v5.9.0:
          image: "php:latest"
      - artifacts#v1.9.3:
          download: "vendor"
          compressed: vendor.tgz
