steps:
  - label: ":fastlane: Test"
    key: test
    commands:
      - "bundle install --path vendor/bundle"
      - "bundle exec fastlane ios test"
    env:
      LC_ALL: "en_US.UTF-8"
    artifact_paths:
      - "fastlane/test_output/**/*"

  - label: ":buildkite: Annotate"
    depends_on: "test"
    allow_dependency_failure: true
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: fastlane/test_output/*.junit

  - label: ":fastlane: Lint"
    commands:
      - "bundle exec fastlane ios lint"
    env:
      LC_ALL: "en_US.UTF-8"

  - label: ":fastlane: Build"
    key: build
    commands:
      - "bundle install --path vendor/bundle"
      - "bundle exec fastlane ios build"
    env:
      LC_ALL: "en_US.UTF-8"

  - label: ":ios: Submit beta"
    depends_on: build
    branches: "beta beta/*"
    commands:
      - "bundle install --path vendor/bundle"
      - "bundle exec fastlane ios beta"
    env:
      LC_ALL: "en_US.UTF-8"
