steps:
  - label: ":bundler: Install dependencies"
    command: "bundle install --path vendor/bundle"
    key: "deps"

  - label: ":fastlane: Test"
    command: "bundle exec fastlane ios test"
    depends_on: "deps"
    env:
      LC_ALL: "en_US.UTF-8"

  - label: ":fastlane: Lint"
    command: "bundle exec fastlane ios lint"
    depends_on: "deps"
    env:
      LC_ALL: "en_US.UTF-8"

  - label: ":fastlane: Build"
    command: "bundle exec fastlane ios build"
    depends_on: "deps"
    env:
      LC_ALL: "en_US.UTF-8"
    artifact_paths:
      - "fastlane/test_output/**/*"