steps:
  - label: ":npm: Install dependencies"
    key: "deps"
    command: npm install
    plugins:
      - artifacts#v1.9.3:
          upload: "node_modules"
          compressed: node_modules.tgz
      - docker#v5.9.0:
          image: "node:latest"

  - label: ":eslint: Run ESLint"
    command: "npx eslint"
    depends_on: "deps"
    plugins:
      - artifacts#v1.9.3:
          download: "node_modules"
          compressed: node_modules.tgz
      - docker#v5.9.0:
          image: "node:latest"

  - label: ":jest: Run unit tests"
    depends_on: "deps"
    command: "npx jest"
    plugins:
      - artifacts#v1.9.3:
          download: "node_modules"
          compressed: node_modules.tgz
      - docker#v5.9.0:
          image: "node:latest"

  - label: ":cypress: Run cypress tests"
    depends_on: "deps"
    commands:
      - npm install
      - npm start & npx --yes wait-on http://localhost:8000
      - npx cypress run
    plugins:
      - docker#v5.9.0:
          image: cypress/browsers:node18.12.0-chrome106-ff106
          options: --user 1001
          volumes:
            - /workdir/node_modules
