steps:
  - label: ":nodejs: Install dependencies"
    key: "deps"
    commands: npm ci
    plugins:
      - docker#v5.9.0:
          image: "node:${NODE_VERSION:-latest}"

  - label: "Build"
    depends_on: "deps"
    commands: npm run build
    plugins:
      - docker#v5.9.0:
          image: "node:${NODE_VERSION:-latest}"

  - label: "Run tests"
    depends_on: "deps"
    commands: npm test
    plugins:
      - docker#v5.9.0:
          image: "node:${NODE_VERSION:-latest}"
